# Generated by Django 3.0.7 on 2020-07-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TextManage', '0002_auto_20200714_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFreq',
            fields=[
                ('wordid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=45)),
                ('frequency', models.CharField(max_length=5)),
                ('ttextmanageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextManage.TextMange')),
            ],
            options={
                'db_table': 'wfreq',
            },
        ),
    ]
