# Generated by Django 3.0.5 on 2020-07-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_auto_20200624_1740'),
        ('TextManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmange',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='usermanage.TUser'),
        ),
    ]
