# Generated by Django 3.0.7 on 2020-06-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tuser',
            table='TUser',
        ),
    ]
