# Generated by Django 3.0.7 on 2020-08-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_auto_20200624_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=45)),
                ('admin_pwd', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
