# Generated by Django 3.0.7 on 2020-08-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_pwd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_username',
            field=models.CharField(max_length=50),
        ),
    ]
