# Generated by Django 3.0.7 on 2020-08-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_auto_20200802_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Adminuser',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='adminid',
            new_name='adminuserid',
        ),
    ]
