# Generated by Django 3.0.7 on 2020-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_auto_20200802_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('admin_userid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.DeleteModel(
            name='Adminuser',
        ),
    ]
