# Generated by Django 3.0.7 on 2020-08-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0006_auto_20200802_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin_user',
            table='Admin_user',
        ),
    ]
