# Generated by Django 3.0.7 on 2020-08-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0007_auto_20200802_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminuserid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.DeleteModel(
            name='Admin_user',
        ),
    ]
