# Generated by Django 3.0.7 on 2020-08-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0008_auto_20200802_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
