# Generated by Django 3.0.7 on 2020-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0009_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administer',
            fields=[
                ('adminuserid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Administer',
            },
        ),
    ]
