# Generated by Django 3.0.7 on 2020-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0010_administer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminuserid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='TextAdmin',
            fields=[
                ('TextAdmin_userid', models.AutoField(primary_key=True, serialize=False)),
                ('TextAdmin_username', models.CharField(max_length=50)),
                ('TextAdmin_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TextAdmin',
            },
        ),
    ]
