# Generated by Django 3.0.7 on 2020-08-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0011_admin_textadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
