# Generated by Django 3.0.7 on 2020-08-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0012_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administer',
        ),
    ]
