# Generated by Django 3.0.7 on 2020-08-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0013_delete_administer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextAdmin',
        ),
    ]
