# Generated by Django 3.0.7 on 2020-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0015_tadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAdmin',
            fields=[
                ('tadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('tadmin_name', models.CharField(max_length=45)),
                ('tadmin_pwd', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TextAdmin',
            },
        ),
    ]
