# Generated by Django 3.0.7 on 2020-08-03 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0018_maincontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontrol',
            name='admincreatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tuser',
            name='usercreatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
