# Generated by Django 3.1 on 2020-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0019_auto_20200803_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
    ]
