# Generated by Django 3.1 on 2020-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0020_admin_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadmin',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
    ]
