# Generated by Django 3.1 on 2020-08-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0021_tadmin_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
